### ISSUE TITLE
Exception on Windows 10  19043

### ISSUE THREAD

**Issue by sfranky** [darkguy2008/Switchie#1]
The pager opens after this exception message, but is empty!
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Runtime.InteropServices.COMException (0x80070490): Element not found. (Exception from HRESULT: 0x80070490)
   at Switchie.VirtualDesktopAPI.Win10.WindowsVirtualDesktopAPI.IApplicationView.GetAppUserModelId(String& id)
   at Switchie.VirtualDesktopAPI.Win10.WindowsVirtualDesktopManager.PinApplication(IntPtr hWnd)
   at Switchie.MainForm.OnShown(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnShown(EventArgs e)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4470.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Switchie
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/sfranky/Downloads/Switchie.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4400.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4470.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

```

**Comment by darkguy2008** [comment]
Hey!

Thanks for reporting this issue! Sorry for the delay 😅

While I was unable to reproduce this while debugging in 19043 versions, I was able to reproduce it while running it in 19042, so I've made a small patch and released a new version. Please give it a try - I hope it works better for you! 😊

Thanks!

![19042 20H2 2022-04-13_21-49](https://user-images.githubusercontent.com/6304136/163315450-f8be6dc5-5cc0-4326-80e7-7f7fa4083fab.png)

![19043 2022-04-13_22-09](https://user-images.githubusercontent.com/6304136/163315452-d5b6f529-5ab8-4619-9272-bae95a17b720.png)

![19043 2022-04-13_22-32](https://user-images.githubusercontent.com/6304136/163315453-051df4ea-e0b5-40ad-a40b-9e580b6ba54d.png)

**Comment by sfranky** [comment]
I'm happy to report it works on both windows 11 AND windows 10 19043 !
many thanks!! i like the implementation, it's light and fast, the window on the bottom is unobtrusive, and makes a hell of a difference when using the multiple desktops feature of windows!
Now all I need is a "move win to Desktop #" (edit: in general, not from Switchie!!) and I'm done :D   
Thanks again!

**Comment by darkguy2008** [comment]
> I'm happy to report it works on both windows 11 AND windows 10 19043 ! many thanks!! i like the implementation, it's light and fast, the window on the bottom is unobtrusive, and makes a hell of a difference when using the multiple desktops feature of windows! Now all I need is a "move win to Desktop #" (edit: in general, not from Switchie!!) and I'm done :D Thanks again!

Thank you for your feedback! :D indeed it's something that Windows is really missing, good thing there's an API to interact with them (although it's not easy, COM sucks :P) and I was kinda baffled that there wasn't a single app that would work like this (or people who were missing the pager in Linux) so had to write my own 😅

I think there should be apps that can allow windows to be moved to other desktops. I could give a try for Switchie to implement that, but I'm not sure if it requires a global hook or something that'll trip off AVs, so I'll have to check, but good suggestion, and I'm glad it works for you now! Hope it helps for your productivity! :D
